### ISSUE TITLE
Make Exceptions Serializable

### ISSUE THREAD

**Issue by pwiens** [microsoft/testfx#113]
## Description
Currently `AssertFailedException`, `AssertInconclusiveException`, `InternalTestFailureException`, and `UnitTestException` are not marked serializable.

This presents a problem when executing tests in an different AppDomain. Since the exceptions are not serializable the runtime can't move them between app domains and throws SerializationException.

[AB#1575813](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1575813)

**Comment by PablitoPaul** [comment]
Any news about this problem? I must migrate a _lot_ of existing test projects to the new MsTest.TestFramework, but many of them use AppDomains (to be able to unload assemblies). If AssertFailedException etc are not serializable, the output of a failed test is just "_AssertFailedException in assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable_", instead of the real failure reason.

**Comment by AbhitejJohn** [comment]
I've since been working on other projects. @cltshivash and @jayaranigarg would be good contacts to help get traction on this.

**Comment by Evangelink** [comment]
We need a bit of investigation but maybe we will have to wait for the v3 as `SerializableAttribute` isn't available in portable class libs.
