### ISSUE TITLE
DataRowAttribute supported arguments are to limited

### ISSUE THREAD

**Issue by jay1891** [microsoft/testfx#1503]
Dear,

We use 25 constructor arguments on the DataRowAttribute, but with version 3.0.0 it is no longer possible.

Is it please possible to add them again?

**Comment by Evangelink** [comment]
Hi @jay1891,

Sorry we broke you. Here is some more information about the reasoning behind our change:

> To give you a bit of context on this change. The older MSTest were using object, params object[] signature which was causing issue when trying to pass 2 arrays. Looking at xUnit and NUnit it seems they are using params object[] signature but doing so it's becoming impossible to pass string array as argument (compiler error). After some investigation, we decided to follow the pattern used by runtime for Action (with 16 overloads). Looking up online on GitHub we didn't see many repositories using this many parameters and thought it was "relatively" safe.

I will keep this issue open and discuss it with the team.

**Comment by steiner2789** [comment]
Hello everyone,

I faced the same issue as we have unit tests with 20 DataRowAttribute arguments. Luckily there are just a few test that are now broken and I worked around this issue by simply using e.g. string arrays instead of separate string parameters to reduce the number of parameters.
So I guess this breaking change is acceptable.

**Comment by RichardCrawshaw** [comment]
I've got a number of tests that use a lot of parameters, including a final params object[] parameter. Restricting to just 16 would break a lot of them. :-(

**Comment by Evangelink** [comment]
Sadly there is no good solution as the initial design was bad and was causing issues.

Basically, we have the following options:

1. `DataRow(params object[] args)`. We break cases were people pass array of string.

1. `DataRow(object arg1, params object[] args)` the one from previous version. With this one it's impossible to pass 2 arrays and you need to wrap the second array into an array otherwise compiler complains.

1. Solution we have with multiple overloads. Main problems is how many args shall we accept. We decided to follow runtime recommendations (what they use for `Func`, `Action`...).

I will make sure to raise that point in today's meeting.

**Comment by Evangelink** [comment]
Here after are some details about problem with v2 and leads we explored to try to fix the issue.

Prior to v3, `DataRowAttribute` was having the following ctors:
- `DataRowAttribute()` 
- `DataRowAttribute(object data1)`
- `DataRowAttribute(object data1, params object[] moreData)`

Because of that it was not possible to provide exactly 2 parameters with the 2nd parameter being an array (e.g. `DataRowAttribute(1, new object[] { 1, 2, 3 })`) as the 2 parameter was considered as they params array and unwrapped resulting into `1, 1, 2, 3` being passed to the method and so having signature conflict.

We tried to refactor to have only `DataRowAttribute(params object[] args)` but this is leading to the following 2 issues:
- `DataRowAttribute(new string[] { "a" })` is no longer compiling because string array is not a constant expression
- `DataRowAttribute(new object[] { 1, 2 })` is facing the same issue as the 2nd parameter was facing in the v2 and is unwrapped.
See https://github.com/microsoft/testfx/pull/1446

After some more investigation, the only reasonable solution we found is to have multiple overloads of the ctor with one more object. To find the "right" upper bound, we looked at what was done by runtime (`Func`, `Action`...), at the usage of `DataRowAttribute` on GitHub and some coding guidelines on number of parameters to a method.

@RichardCrawshaw if you are using `MyTestMethod(TypeA a, TypeB b..., params object[] remainingArgs)` kind of signature you could update your `DataRow` line to wrap the extra args in an array (e.g. `[DataRow(1, 2.. 15, new object[] { 16, 17, ... , 50 })]`).

@jay1891 I will keep this issue open for some time to see if more people are bothered by this change but at the moment it seems to be the best compromise we have.

**Comment by jay1891** [comment]
@Evangelink We discussed it internally and we will plan to improve our tests that are not compiling. I understand there are multiple reasons to no longer provide it, and I think it is understandable. Thank you for the update!

**Comment by RichardCrawshaw** [comment]
Just wondering if this could be solved, or at least made easier by sub-classing the attribute class, or a partial class, that the test writer could write for their exact circumstances. I'm away from computer ATM so this is nothing more than a brain dump that could be complete garbage. It would need reflection to call the test but that could be assisted by protected methods in the base attribute class so there would be nothing more needed than to call Invoke on the MethodInfo of the test method and supply the required set of supplied parameters.

**Comment by Evangelink** [comment]
You can definitely create your own attribute that inherits from `DataRowAttribute` to allow `params object[]` signature.

**Comment by sjc9999** [comment]
I have some DataRows with length up to 20 or more.
Is there a work around?
Can unlimited DataRow length be added back?

**Comment by DanMcNamee** [comment]
So, you couldn't make a new attribute [DataArrayRow] so that people that wanted that functionality could have it and not break all the code of people who are already using [DataRow]?  You have broken something already in use, to give functionality not yet in use because it wasn't possible in the existing structure.

**Comment by henning-krause** [comment]
I just ran into this exact issue and solved it by creating my own DataRowAttribute class:

```cs
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public class ExtendedDataRowAttribute : Attribute, ITestDataSource
{
	private readonly object[] _Data;

	public ExtendedDataRowAttribute(params object[] data)
	{
		_Data = data;
	}

	public IEnumerable<object[]> GetData(MethodInfo methodInfo) => new [] {_Data};

	public string GetDisplayName(MethodInfo methodInfo, object[] data) => data != null ? string.Format(CultureInfo.CurrentCulture, "{0} ({1})", methodInfo.Name, string.Join(",", data.AsEnumerable())) : null;
	}
```

**Comment by Evangelink** [comment]
Hi folks,

Thank you for your patience! We managed to update MSTest to remove the limitation of arguments for the datarow. 

Please feel free to update to `3.0.3` and let us know if there is still any issue remaining for you.
