### ISSUE TITLE
Support for older .NET Frameworks

### ISSUE THREAD

**Issue by leopignataro** [Microsoft/testfx#196]
Dear testfx team,

Are there plans to support older .NET Frameworks, such as 4.0 (and perhaps even 3.5)?

This seems to be a gap. On the MS docs topic [Developing Libraries with Cross Platform Tools](https://docs.microsoft.com/en-us/dotnet/core/tutorials/libraries), net40 is even suggested as a good baseline:

> If you want to reach the maximum number of developers and projects, use the .NET Framework 4.0 as your baseline target.

However, test projects created with "dotnet new mstest" and targeted to net40 don't run with "dotnet test". The reason for this seems to be that the packages MSTest.TestAdapter and MSTest.TestFramework don't support .NET Framework 4.0.

We have a class library multitargeted to .NET Frameworks 4.0 and 4.5, currently working on adding support for .NET Standard 2.0. We currently have separate test projects for each supported platform, with a trick to reuse the actual test code. It would be wonderful to have a single test project.

**Comment by AbhitejJohn** [comment]
@leopignataro : Thanks for bringing this up. There aren't any plans to support .Net 4.0 or lower in the near future given the delta in terms of support matrix from [net40](https://www.microsoft.com/en-in/download/details.aspx?id=17851) to [net45](https://www.microsoft.com/en-in/download/details.aspx?id=30653) isn't large. We haven't also heard back from a lot of users about wanting this. 

On a side note, the core of MSTest V2 is built for netstandard 1.0 (equivalent to net45) so it works cross-platform. Moving it to net40 would require a code split and a bunch of #if statements since not all the APIs we require are similar in lower .net frameworks. 

/cc: @pvlakshm.

**Comment by abatishchev** [comment]
What prevents you from targeting the latest and greatest framework from your tests? You always can continue to target whatever you'd like from the app itself.

**Comment by igitur** [comment]
@abatishchev One often wants to test features specifically designed around older targets. I have a lot of `#if _NET35_` conditional compiler statements in my code where I have to introduce workarounds because of lacking features in .NET3.5. I definitely want to have unit tests for those workarounds.

**Comment by abatishchev** [comment]
@igitur fair point, thanks for the explanation

**Comment by leopignataro** [comment]
Precisely as @igitur explained. Moreover, it is not uncommon for packages to have different dependencies for each target platform. Therefore, it is important to test each implementation, which might rely on an entirely different set of dependencies.

**Comment by pvlakshm** [comment]
Please see [comment](https://github.com/Microsoft/testfx/issues/196#issuecomment-307566092). This is not in plan.
