### ISSUE TITLE
rename vstest-filter to just filter

### ISSUE THREAD

**Issue by jpribele** [microsoft/testfx#2002]
## Summary

Its a bit weird that is different. the docs reference in the command line output says `filter` 

## Background and Motivation
easier to use. don't need to switch arguments when changing between the two runners

[AB#1934380](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1934380)

**Comment by Evangelink** [comment]
The main motivation for this new wording was that we wanted to introduce a new filter system by default (this had to be postponed) because there are many confusions around the vstest filter between the various test frameworks.

I'll keep this open so we can decide if we will manage to implement the new filter quickly and so it might be worth to keep current shape or if we think this will be delayed and it's better to change.

Please if you have any other feedback let us know this is super valuable for us to be able to fine tune the runner.

**Comment by Evangelink** [comment]
Hey @jpribele! We had a quick chat with the team and we decided to rename the filter and the runsettings command line options to match those of `dotnet test` command

**Comment by Evangelink** [comment]
Done
