### ISSUE TITLE
When using filter retry does not work

### ISSUE THREAD

**Issue by zelda1link3** [microsoft/testfx#2205]
When using a filter with the retry on percentage. I expect that the percentage is used on the filtered tests but the tests wont retry.

**Comment by MarcoRossignoli** [comment]
Can you elaborate?

the `--retry-failed-tests-max-percentage` means that if we have more than that % of failed tests at first round we won't retry, this is for instance when you have infrastructure issues and so there's not sense to retry and we return with a failure immediately.

For instance suppose to have 2 test and 1 is failing and run a command line like

```
mytest.exe --retry-failed-tests 2 --retry-failed-tests-max-percentage 50 --filter Name~TestMethod1|Name~TestMethod2
```
In this case we will retry  because we have 50% of tests failing(1 out of 2) so we respect the threshold 

In case of 
```
mytest.exe --retry-failed-tests 3 --retry-failed-tests-max-percentage 49 --filter Name~TestMethod1|Name~TestMethod2
```
In this case we won't retry because we failed the 50% (1 out of 2)and we set a max threshold to 49%.


Can you provide a repro of you case?

**Comment by Evangelink** [comment]
Moving to 3.3

**Comment by Evangelink** [comment]
@zelda1link3 I am closing this ticket, please let us know if you are still experiencing any issue.
