### ISSUE TITLE
DataRow behavior for arrays changed from 1.4.0; now null creates an empty array with a null item for object types

### ISSUE THREAD

**Issue by gorygregory** [microsoft/testfx#2266]
## Steps To Reproduce

Minimal CSPROJ:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.2.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.2.0" />
  </ItemGroup>

</Project>
```

Minimal code:

```csharp
namespace ReproMsTestBug
{
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class ReproDataRowBug
    {
        [DataRow(null)]
        [TestMethod]
        public void DataRowInput_ArrayShouldBeNull_GivenNullObjects(object[] input)
        {
            // expected collection should be null
            Assert.IsNull(input);
        }
    }
}
```

## Expected behavior
Test is expected to pass when using v3.2.0 of `MSTest.TestAdapter` and `MSTest.TestFramework`

## Actual behavior
Test fails because input is actually an array with a single null item

## Additional context
You can easily switch the package references for `MSTest.TestAdapter` and `MSTest.TestFramework` to v1.4.0 and see the test pass.

**Comment by nohwnd** [comment]
This works good all the way down to the executor (your parameter is passed as [null]), but the executor checks if the receiver is object[] and wraps it.


[DataRowAttribute supported arguments are to limited · Issue #1503 · microsoft/testfx (github.com)](https://github.com/microsoft/testfx/issues/1503)


I don't fully get why this was done, probably to fix one of the cases mentioned here: https://github.com/microsoft/testfx/issues/1503#issuecomment-1378463341

I don't see any workaround that you could apply right now.

**Comment by nohwnd** [comment]
This looks like the case that this condition is supporting, where test previously provided array of data, that would map to array parameter. 

```cs
[TestMethod]
[DataRow(new object[] { 1, 2 })]
public void TestMethod2(object[] a)
{
}
```

This works in 2.2.10 (latest 2.x version), and is broken in 3.x.x. If we want to special case this scenario above, we should move the fix up from executor to the attribute, and wrap the array there. That should give the same new experience, minus the breaking change.

**Comment by Evangelink** [comment]
I have just done some debugging and the main problem is that on v1 and v2, MSTest was having (amongst other overloads) `DataRowAttribute(object o, params object[] remaining)` which means that when passing a single array it was wrapped as `object` and all was good. But there were some problems when you wanted to provide an array as 2nd argument. In v3, we fixed the issue of passing an array to the 2nd arg but broke some cases that were working before (and were not tested locally).

The main problem we have is that inside `DataRowAttribute`, we are not able to differentiate between `[DataRow(null)]` and `[DataRow(new object[] { null })]` as for the compiler providing a single array doesn't mean you want to provide 1 arg of type array that contains null but instead that the full array you provide contains only 1 argument that is null. Another example (because null is always strange), is that `[DataRow(1, 2)]` is the same as `[DataRow(new object[] { 1, 2 })]` for the compiler while for the user the 2 cases are pretty different.

I don't think we have a good way (avoid breaking change) to fix that case while keeping reflection as the behavior is defined by .NET compiler/runtime.

I have also tried to break public API and make `Data` property nullable but the engine is doing many tricks so we end up in the same situation. I believe source generator is the way to go.

**Comment by nohwnd** [comment]
> The main problem we have is that inside DataRowAttribute, we are not able to differentiate between [DataRow(null)] and [DataRow(new object[] { null })]

I don't see that: 

https://sharplab.io/#v2:C4LgTgrgdgPgAgJgAwFgBQiCM65IARyYB0AMgJZQCOA3DvoUQEoCmAZgDbMDGwZA9lFpocAZgIICmAOx4A3nnR4lBMYQBsBACx4AsgEMKeABQBKOYuWWAbnrB4ueALx5gATwAOzPqyMBhE0QA4szAvhAAzsB8ALYAgsDAYGQARhDAzOEAPAAiesB6AHymRAAqfLFgYHqupkKWlhb19kQAklDhnjy1jfVcANpIALpEAGp67BAZre2dwLVNSj2W/ZjDYxNTbR3ccybUCwpoB/0Ia+OT4dPbXXtLyv0iZxuXW7PdR8oAvujo38JofVy+SMUAg7HYJkG6EBeT0IOYAHc8HxkgArHZ9QZyPCg8F4T6Q6FAuGYAA0CEJAOJ8KRKPRPEx2LJEgJUP+cFUEl82L+0PiiRSaWYAFVwnoAObMIw2dhkAAmAHkoCA8Pykql0iVbJLgJdfOw9OFwqTVeC+AidGDeO5OE4XJBmJSOeI8MS8Cq1YL0uhZD1nXSMVj1hc5DrqH9LM7qe5bHpouFkWjA3gZRcTD1fR8msGMnbUxk6l9fkA==

I can see difference between null, and [ null ]. It is the code in DataRow that is making sure that both will end up the same data ?? [null].
