### ISSUE TITLE
DeploymentItem Analyzer

### ISSUE THREAD

**Issue by fforjan** [microsoft/testfx#2499]
## Summary

We would like to have an analyzer which detects and deprecates the usage of DeploymentItem.
It should be off/info by default.

## Background and Motivation
From #2489 it seems DeploymentItem is potentially deprecated but, also agreed, brings pain.
We would like, while migrating or created new project, ensure that developers do not use anymore DeploymentItem.
We would manually switch the rule to error and do exclusion as info/warning for projects which need to be more away from DeploymentItem

## Proposed Feature

Introduce a new mstest code analyzer which detect the usage of DeploymentItem and info/warnings the developer to not use it.

## Alternative Designs

We were thinking to have our own code analyzer rule which detect deploymentitem usage but would be better integrated into MSTest :)

**Comment by MarcoRossignoli** [comment]
Hi @fforjan sorry for the confusion I didn't say that we will deprecate the feature I said that "I'd like" to deprecate but we don't have any plan and feedback yet so don't worry for now. If and when we deprecate something will be announced and give enough time to migrate to a better solution.

I'm going to close this issue because we're not deprecating this feature.
