### ISSUE TITLE
What is the policy around custom metadata/properties in TestNode? How do capabilities factor in?

### ISSUE THREAD

**Issue by bradwilson** [microsoft/testfx#2546]
As part of #2538 there's some discussion related to using metadata to differentiate between two similar but not identical states (in this case, it's differentiating between a test which is skipped vs. explicit, when both are reported via state as "skipped").

Since I'm considering using the test platform API for my own 1st party support (that is, when using a multi-assembly runner like `xunit.v3.console.exe`), I want to understand what the policies/best practices/etc. are going to be around adding custom metadata. There appears to be the ability to add generalized key/value metadata to the `TestNode` via `KeyValuePairStringProperty` which I assume is meant to allow 1st and/or 3rd party metadata to be added. Is there a structure for this? In the [test node API](https://github.com/microsoft/testfx/blob/main/docs/mstest-runner-protocol/001-protocol-intro.md#test-node) I see dotted names for metadata that would imply a bit of structure (for example, all the location data being represented as properties under `location.*` property names). In `Microsoft.Testing.Extensions.VSTestBridge.ObjectModel.ObjectModelConverters` I see several properties being added with undocumented names (starting with keys like `vstest.*`) in response to client sniffing:

```csharp
if (!(client.Id == WellKnownClients.VisualStudio))
{
	continue;
}
```

How does/should this factor into the capabilities model? If for example we were to add a 1st-party only set of metadata, should we gate this behind a capabilities negotiation so that metadata only shows up on the `TestNode` when we are explicitly expected to have it (because we know the runner is `xunit.v3.console` and not `dotnet test`)? Is this capabilities negotiation described anywhere in documentation yet?

Also, where is this client interaction going to be documented? Right now I found it by randomly poking through the decompiled source for VSTestBridge, but I assume that if/when I were to start directly reporting tests to Test Explorer, I would also need/want to fill in much of the same information that the test bridge does.

**Comment by MarcoRossignoli** [comment]
I will let @drognanar answer to this question on the experimental protocol layer.

**Comment by drognanar** [comment]
In general, the protocol exposes an open set of properties for the `TestNode`.

The non-namespaced properties are the core ones, that we'd expect all clients/servers to understand. The ones that are optional and might only apply to some clients/servers should be namespaced, which is why we added the `vstest.*` properties. So, I'd expect there to be `xunit.*` properties specific to xunit. @evangelink might be able to fill in more information related to the property namespacing.

Also, the `vstest.*` properties are meant to help with vstest interop only. They for instance allow to run a `TestNode` back via `vstest.console` or to write a bridge that takes the old test adapter that relies on TestPlatform's ObjectModel and exposes that to the VS. However, if you're writing a new test runner that does not depend on the legacy TestPlatform's ObjectModel, you might not intend to support such an interop and as such these properties aren't needed. For instance, a new runner written in nodejs should not set any `vstest.*` properties on their `TestNodes` and any and all functionality in VS should be available without these properties.

For instance if `vstestProvider` capability is set, VS will parse the vstest's FQN to get the fully qualified name of a test. However, without this capability set, VS only relies on the `uid` of the `TestNode`.

As far as I recall, the `vstest.*` properties that are documented are the ones that VS will treat specially in the interop mode, but I can check if there's more that need to be added to the document.

**Comment by drognanar** [comment]
On the topic of capabilities currently, the `TestNode` properties are not handshaked, i.e. you can add more metadata to the TestNode and we will store its serialized format.

However, for the overall TestNode's payload size, you might want to add a capability on the client side, like `suboutcomeSupport` and then add the corresponding `xunit.suboutcome` property on the TestNode only if the client expresses that capability.

I'd like to emphasize here is that the spec was the initial release of the protocol. If we can see that a given set of properties features would be generalizable to test runners/clients, we can add that set of capabilities to the protocol. We didn't want to write down in the initial release a set of capabilities that would only apply to one client, just like `vstest.*` properties aren't part of the core standard, but an extension of it. Neither did we want to add capabilities that are added to the spec, but aren't used by any clients/test runners.

For instance, if there's many clients that need a very different set of properties (for instance you only want to see the test name and outcome) and there's significant performance benefits to send fewer properties, we can add the client side capability, where the client would inform the test runner of properties that it uses for UI/UX purposes. It still would be the case that the test runner can add additional properties like `xunit.serializedTestCase` that it uses for non-display purposes. The client should not reject `TestNodes` that have properties it does not understand.

Similarly, we had planned to add a capability to express suboutcomes, but didn't end up adding it to the spec, since VS does not currently make use of such a property.

Here we had two options:

* the client lists the outcomes it supports. If the client supports an `explicit` outcome, the server can send back explicit as outcome. However, if the client does not support an `explicit` outcome, the server must send back one of the outcomes the client supports.
* the client handles suboutcomes and the server adds a suboutcome property to the TestNode. To VS it would be just a display string that it could use to sort/filter tests, but for instance the xunit client could use that for improved UX
