### ISSUE TITLE
Introduce `[STATestMethod]` and `[STATestClass]`

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#2688]
Instead of forcing all tests to be on STA, we could offer the ability to only create a custom thread for the few methods that needs to be STA. This should provide a performance boost.

AB#2078830

**Comment by Evangelink** [comment]
Given some requests we have received, I am wondering if we should introduce either a different attribute or have a "property" on the various places where we want to add this support. 

My main concern with `[STATestMethod]` and `[STATestClass]` is that there will be no way to enable STA threading for Assembly/Class Initialize/Cleanup methods outside of turning the full application to STA.

I would be tempted to vote for a "property" rather than a new attribute because the new attribute will also put us on the corner of having users trying to put the attribute in locations not expected/supported.

As for the design, I think we should support the following scenarios:

1. Full test cycle (ctor, test initialize, test method, test cleanup, dispose) are STA
2. All test cycles from current class are STA
3. Pair AssemblyInitialize/Cleanup and/or ClassInitialize/Cleanup are STA

I don't think there is a strong need to support something more fine-grained (like only ctor, only test method but not init/cleanups...).

**Comment by nohwnd** [comment]
`[STATestClass]` seems like a good enough granularity, given that we don't have the ability to run multiple assembly level setups. It also seems reasonably easy for users to simulate assembly level setup with a lock and static. And also to split tests into needs STA classes and does not need STA classes.

maybe the requirements are different, but no matter how I look at the scenarios I can come up with in my head, STATestClass is practical for all of them, as long as there is also a way to run everything in assembly with STA mode (which there is because it motivates this feature request).

**Comment by Evangelink** [comment]
That's a pretty clever suggestion! I think this is the right next increment, we can adjust based on users/customers feedback.

@nohwnd We consider `[ClassInitialize]` and `[ClassCleanup]` to be part of the STA thread execution, right?

**Comment by Nirmal4G** [comment]
Why not `[TestClass(Threading = ApartmentState.STA)]` or `[TestMethod(STA = true)]` or `[TestMethod, STAThread]`?

These gives better visibility and resuse of existing knowledge with types than creating an entirety new attributes just for specifying threading model. Also, there's an existing type in the BCL for threading model that we can use it here.

BTW, I vote for the middle one. It's simple. The existing attributes can be declared only on methods. The first two allow parameterization that'll allow changing at Runtime but the enum one is too longer to type.

**Comment by Evangelink** [comment]
@Nirmal4G Thanks for your input!

MSTest is mainly relying on attributes to configure test execution (e.g. `[Timeout]`, `[Ignore]`...) so we decided to follow a similar pattern here. As for the `[STAThread]`, we are thinking about adding wider support for threading (including synchronization context) that would result in inconsistencies between declarations. Also, note that `[STAThread]` attribute description would be inacurrate if reused for our context as the "application" threading model wouldn't be changed.

**Comment by Nirmal4G** [comment]
The `[STAThread]` attribute applies to Methods. If applied on a Main method then the host runner would run in that threading model, if on any other method it is expected to run that method in that model but I don't know how the Runtime handles that, so, I'm not assuming.

An attribute neither define a behavior nor enable them. It merely is a marker. It's up to the Runtime or Host Runner to make use of the attributes to enable the behavior.

With that said, I merely made the suggestion to reuse the existing types instead of declaring a new one if we're going the **NEW** attribute route. But IMO, adding a property (like `STA`) to the already existing attributes would suffice instead of making the Runtime work for the tests.

**Comment by Evangelink** [comment]
Moving out of current iteration as we will not have enough time to validate all scenario.
