### ISSUE TITLE
Test run does not fail in case something fails in TestCleanup/AssemblyCleanup/ClassCleanup

### ISSUE THREAD

**Issue by sudiptadmsft** [Microsoft/testfx#270]
Test run doesn't fail at all. Ideally they should fail so that troubleshooting is easy
```
{
        [TestMethod()]
        public void addTest()
        {
            var i = new SimpleMath.Add().add(5, 4);
            Assert.AreEqual<int>(9, i);//
        }
        [AssemblyInitialize()]
        public static void AssemblyInit(TestContext context)
        {
            Console.WriteLine("Assembly Init");
        }
        [ClassInitialize()]
        public static void ClassInit(TestContext context)
        {
            Console.WriteLine("ClassInit");
        }
        [TestInitialize()]
        public void Initialize()
        {
            Console.WriteLine("TestMethodInit");
        }
        [TestCleanup()]
        public void Cleanup()
        {
            Console.WriteLine("TestMethodCleanup");
            throw new Exception("Thrown from AssemblyCleanup()");
        }
        [ClassCleanup()]
        public static void ClassCleanup()
        {
            Console.WriteLine("ClassCleanup");
            throw new Exception("Thrown from ClassCleanup()");
        }
        [AssemblyCleanup()]
        public static void AssemblyCleanup()
        {
            Console.WriteLine("AssemblyCleanup");
            throw new Exception("Thrown from AssemblyCleanup()");
        }
    }
```

**Comment by AbhitejJohn** [comment]
@sudiptadmsft: An exception in TestCleanup does fail the test. Issues in Class/Assembly cleanup are logged as warnings. I'm not sure if we should fail all the tests in the assembly/class if there is an issue in their cleanups. Changing that would be a DCR because we will have to hold on to all the TestCase objects until their cleanups are done to mark their outcomes accordingly which could bring up all sorts of issues.
This is the same behavior as mstest v1 and IMHO we should leave it as is.
/cc: @pvlakshm.

**Comment by codito** [comment]
Tagging @acesiddhu for thoughts, I think this issue came from a related one filed in internal vsts repo.

**Comment by pvlakshm** [comment]
An exception in TestCleanup does fail the test. Issues in Class/Assembly cleanup are logged as warnings. This is by design.
