### ISSUE TITLE
No Source Available in Test Explorer

### ISSUE THREAD

**Issue by jackbond** [Microsoft/testfx#274]
## Description
In the Unit Test Explorer I can see and run a unit test, but when I select the test it displays on the bottom, "No source available"

## Steps to reproduce
I created a unit test project, and converted it to use the new project file format with PackageReferences. I added two Nuget packages, MSTest.TestAdapter and MSTest.TestFramework.

## Expected behavior
I should be able to double click a test to navigate to the code

## Actual behavior
I see a message "No Source Available"

## Environment
Visual Studio v15.3.5
MSTest.TestAdapter v1.1.18
MSTest.TestFramework v1.1.18

I may not have properly converted the project to use the new project format. Is there a sample of a Unit Test project which uses PackageReferences (as opposed to packages.config?)

**Comment by AbhitejJohn** [comment]
@jackbond: I guess the conversion went well because you are able to discover and run tests. There might be something else at play here. Could you turn on TestExplorer diagnostics from Tools -> Options -> Test -> Logging -> Logging Level? Set that to diagnostic and share the logs that show up in the Output->Tests pane with us please.

**Comment by jackbond** [comment]
[repro.zip](https://github.com/Microsoft/testfx/files/1335033/repro.zip)

How about a solution that reproduces the issue?

**Comment by jackbond** [comment]
I've resolved the issue by adding the Microsoft.NET.Test.Sdk Nuget. I skipped adding it originally because its Nuget description reads, "The MSbuild targets and properties for building the .Net core test projects." Perhaps that description could be updated?

**Comment by AbhitejJohn** [comment]
@jackbond: Thanks for the repro. This is a new project system based project where the pdbs generated are portable by default. That explains why the Source Information logic fails since it currently only works on full pdbs. 

Adding `Microsoft.Net.Test.Sdk` package brought in the following 
```
<DebugType>Full</DebugType>
```
ensuring that the scenario works. You could go ahead and keep that package installed(which is added in by default for Unit test templates in the project system).
/cc:  @Faizan2304, @smadala for the package description change.

**Comment by jackbond** [comment]
@AbhitejJohn

Thanks for the info. I converted a few more of our unit test projects, and one of them had an AssemblyInitialize attribute. When I ran a test, I got the error below. I haven't been able to recreate the problem in the repro project I sent you, any possible ideas? Thanks.

Method OurClassName.AssemblyInit has wrong signature.  Parameter 1 should be of type Microsoft.VisualStudio.TestTools.UnitTesting.TestContext.

**Comment by AbhitejJohn** [comment]
@jackbond: Do you have a testsettings file specified for the run? If yes, can you try removing it or replacing with a runsettings instead?

**Comment by pvlakshm** [comment]
Please reactivate if this is still blocking you.

**Comment by johncrim** [comment]
Is there an issue tracking the fact that the test explorer doesn't work with embedded PDBs?

**Comment by smadala** [comment]
@johncrim From **VS 15.5** test explorer should support it, [Source-Information-For-Discovered](https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0010-Source-Information-For-Discovered-Tests.md) should solve the embedded PDBs issue.

**Comment by johncrim** [comment]
Thanks @smadala . I've found that VS 15.5 works with portable symbols, but not embedded. The linked document doesn't provide any additional info on support for portable vs embedded symbols.

**Comment by smadala** [comment]
@johncrim 
From doc:
> Use of better performant Roslyn APIs instead of reflection based approach on **PDBs**. 

Indicates source info determined by Roslyn APIs, It shouldn't be matter what type the PDB is.

Debug type embedded working for me on 15.5.1. See the below image.

![source_info](https://user-images.githubusercontent.com/4337332/34456339-c5008128-edb9-11e7-87b3-4a96cc3046e9.PNG)

**Comment by lostmsu** [comment]
Just FYI, I had this problem with a .NET Console App targeting full framework, referenced from unit tests. Going to settings and setting Build -> Advanced -> Debugging information to Full fixed the problem.

**Comment by jlpaukner** [comment]
Ok ,  I had this issue, but figured it out.    (visual 2022 specflow 3.9.74)
 I had excluded the .cs specflow generated test files from the solution since they are recreated when project is built. 
 The tests run even if the .cs are not included on the solution, but the test explorer only sees the source file only if  included.
![no source](https://user-images.githubusercontent.com/89228704/185934621-0a71f3dc-cbff-437d-8dc4-472b2e8d7411.png)
