### ISSUE TITLE
DataRow DisplayName is not generated properly in .NET Framework when using null values

### ISSUE THREAD

**Issue by Mertsch** [Microsoft/testfx#284]
## Steps to reproduce
Run this test in .NET Framework 4.6.1 mode
```
[TestClass]
public class UnitTest1
{
    [TestMethod]
    [DataRow("OK", "OK Test")]
    [DataRow("OK1", "OK1 Test")]
    [DataRow(null, " Test")]
    public void TestMethod1(string input, string output)
    {
        Assert.AreEqual(output, $"{input} Test");
    }
}
```

## Expected behavior
Should output the same display name as in .NET Core

## Actual behavior
![image](https://user-images.githubusercontent.com/9402861/31330806-2d141b14-ace0-11e7-875f-0a24f08f9283.png)
And even worse with multiple null tests
![image](https://user-images.githubusercontent.com/9402861/31330908-90623aac-ace0-11e7-95ab-429fb476cb38.png)

## Environment
VS 2017 15.3.5
.NET Core 2.0 / .NET Framework 4.6.1
```
<package id="MSTest.TestAdapter" version="1.2.0-beta3" targetFramework="net461" />
<package id="MSTest.TestFramework" version="1.2.0-beta3" targetFramework="net461" />
```

**Comment by jayaranigarg** [comment]
This is essentially an issue with string.join(String separator, object[] values).

If first value is null like in `[DataRow(null, " Test")]` , both .net framework and net core used to return an empty string earlier. But this issue got fixed in netcore to return (,Test) refer this[https://github.com/dotnet/coreclr/issues/4506]. However, it appears that the same fix is not yet ported to .net framework and hence we are observing a difference in behavior.
