### ISSUE TITLE
MSTEST0019/MSTEST0020 vs. MSTEST0021/MSTEST0022

### ISSUE THREAD

**Issue by avivanoff** [microsoft/testfx#2928]
Are [MSTEST0019](https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0019)/[MSTEST0020](https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0020) mutually exclusive with [MSTEST0021](https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0021)/[MSTEST0022](https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0022)? What is MSTest team's recommendation: ctor/Dispose or attributed methods?

**Comment by Evangelink** [comment]
Yes the rules are indeed mutually exclusive. They are all disabled by default because they are more stylistics than anything. Some teams prefer to always see a single pattern being used across all their tests.

I personally would recommend using ctor over TestInitialize (or in combination with) because it will help compiler and some other analyzers with nullability, uninitialized and other state checks. I would use the TestInitialize for anytbing requiring async and anything that could be potentially long operation. For cleaning up resources, I would prefer to always use TestCleanup because I see dispose as more technical.

@MarcoRossignoli @nohwnd what's your opinion (if any)?

**Comment by MarcoRossignoli** [comment]
It's personal and unfortunately this design predates us and can be confusing(more way to do a thing), I would use the test object instance lifecycle and init only if I need async init, ctor is not async

ctor/TestInitialize/test/dispose|disposeasync

**Comment by Evangelink** [comment]
@avivanoff I have done a quick edit of your description only to add links to the rules for reference.

**Comment by avivanoff** [comment]
Agree, it is very confusing. And personally, I prefer not to use TestInitialize/Cleanup and create test collateral right in the test methods.

This leads to the following suggestion. Since there is a new instance of test class created for every test there is not much value in having TestInitialize/Cleanup methods. More that that, there is not much value in ctor/Dispose as it will be called for every test method making it obsolete if collateral/initialization is done in the test methods themselves. I know you are working to deprecate TestContext property in favor of IOC initialization in constructor. Why not just make test methods static where the first argument is TestContext?

**Comment by avivanoff** [comment]
I hope you would be able to deliver it in MSTest v4. And I would love to get my hands on beta/preview bits when available.

**Comment by Evangelink** [comment]
@avivanoff Do you need other info or can we close this discussion ticket?
