### ISSUE TITLE
dotnet vstest -lt questions

### ISSUE THREAD

**Issue by Gustav-Eikaas** [microsoft/testfx#3725]
## Description
Not sure if this is the correct place to ask this but just close the issue if its not. 

Im trying to build a neovim plugin for dotnet development and I am having some issues with discovering MsTests. If a test has the attribute [TestMethod] which I understand is a MsTest attribute. The output of `dotnet test -t` strips the namespace and only gives me the name of the test. Is this intentional? xUnit and nUnit seems to give full namespace

## MsTest output for tests with [TestMethod]
```
dotnet vstest -lt .\bin\Debug\net8.0\Project.Tests.dll
The following Tests are available:
    GetOrCreate_ShouldReturnCachedValue
    GetOrCreate_ShouldReuseCachedValue_BeforeExpirationExpired
    GetOrCreate_ShouldReplaceCachedValue_AfterExpirationExpired
```

## Normally outputted from xUnit and nUnit using [Fact], [Theory] etc..
```
  Project.Tests.Tests.CacheManagerTests.Get_ShouldReturnCachedValue_WhenKnownKey
  Project.Tests.Tests.ViewModels.GetReleaseControlApiModelTests.TestEmptyDataOk
```

Is there a way to get the namespace as part of the output?

**Comment by nohwnd** [comment]
Yes this is intentional. 

dotnet test calls [vstest](https://github.com/microsoft/vstest) which then calls MSTest. The display name of a test is used to show the test in the list. 

There is another mode nowadays, which is [testing.platform](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli). We are currently in the process of integrating it with dotnet test and have an issue created here to improve the output of --list-tests here: https://github.com/microsoft/testfx/issues/3221

If this will also impact VSTest I don't know, but personally I'd like to avoid it. 

For VSTest there is also a better way of automating the platform. The [TestPlatform.TranslationLayer package](https://www.nuget.org/packages/Microsoft.TestPlatform.TranslationLayer) this package creates a session with vstest.console and allows you to automate it without parsing output.  You can see an example (and a easy way to experiment with this here in [vstest repo](https://github.com/microsoft/vstest/blob/main/playground/TestPlatform.Playground/Program.cs#L145) 

This is how VS and VSCode automate vstest to get tests for their interactive views. 

Fot the new testing platform the same capabilities are there, but there is no client in a nuget package yet (that I know of).

**Comment by Gustav-Eikaas** [comment]
Thank you for replying. The TransitionLayer package looks good, I will test it out and see if it solves my problem

You can close this issue if you want.

**Comment by Gustav-Eikaas** [comment]
@nowhnd Okay so I tested a bit and wrote an F# script to discover tests in a project. It works great! Only issue/question I have is, the playground example requires a path to the `vstest.console.exe`. Is there any way to avoid this? It is my understanding that this console is a part of Visual studio installation and not dotnet CLI. 

Does VSCode install Visual studio test tools automatically?

**Comment by nohwnd** [comment]
there is no way to avoid providing path to vstest.console. Vstest.console does all the work, but you can use the one shipped with dotnet SDK. 

![image](https://github.com/user-attachments/assets/72f58adb-f0b6-447c-816d-a24da505b995)

Or you can bundle up with your extension one of the redistributables we produce. 

This is inserted into VS: https://www.nuget.org/packages/Microsoft.TestPlatform
This is inserted into dotnet sdk: https://www.nuget.org/packages/Microsoft.TestPlatform.CLI

**Comment by Gustav-Eikaas** [comment]
Referring to the one bundled with the sdk is perfect! I just wanted to avoid having people installing more than the dotnet sdk if they didnt have to

**Comment by nohwnd** [comment]
You might also find this reply by @rouke-broersma, where he describes how stryker-dotnet uses test platform and why they chose not to use the one in dotnet sdk helpful. 

https://github.com/stryker-mutator/stryker-net/discussions/1962#discussioncomment-2346027

I would also like to bring your attention to the new testing platform that comes bundled with mstest. We don't offer any public client (as described above), but we would be interested in your use case and the kind of data you need, so you could run "natively" on the new testing platform :)

**Comment by GustavEikaas** [comment]
> `but we would be interested in your use case and the kind of data you need, so you could run "natively" on the new testing platform :)`


So basically I tried C# development in Neovim and it was horrible, dotnet has such a massive ecosystem of tooling. So i decided to try and write a dotnet plugin to bring a lot of this tooling into neovim. https://github.com/GustavEikaas/easy-dotnet.nvim. Adding basic functionality for finding sln files, csproj files etc wasnt too hard. But one thing I wasnt satisfied with was the `dotnet test` output. Way too hard to read and work with, especially if more than one test was failing. So I tried to make something similiar to the rider/vs testrunner. Working with lua, dispatching dotnet system commands and parsing output is pretty hard so utilizing F# and fsi makes it a bit easier. Your playground link really helped me improve the testrunner

![image](https://github.com/user-attachments/assets/0b256ad6-b918-4a62-ac15-514d8a041dac)

Down the road im thinking it would be nice if I could run the tests using F# instead of dispatching `dotnet test --filter... --logger=trx...` commands
Seems like this is possible given the links you shared

**Comment by nohwnd** [comment]
That looks great :) 

> Down the road im thinking it would be nice if I could run the tests using F# instead of dispatching `dotnet test --filter... --logger=trx...` commands Seems like this is possible given the links you shared

Yeah, this code has all the basic things: discovery, passing tests to run to the runner, or just giving it dll to run. 

https://github.com/microsoft/vstest/blob/main/playground/TestPlatform.Playground/Program.cs#L145

**Comment by rouke-broersma** [comment]
If interested here is our plumbing to drive the vstest test platform using the translationlayer package:

https://github.com/stryker-mutator/stryker-net/tree/master/src/Stryker.Core/Stryker.Core/TestRunners/VsTest

**Comment by Evangelink** [comment]
@GustavEikaas I'll move the discussion as closed, please feel free to comment/reopen if you consider this as not fixed.

**Comment by GustavEikaas** [comment]
@Evangelink yes, no problem! This issue helped me tremendeously. Thanks for all the help! :D
