### ISSUE TITLE
Patch 3.6.2 breaks build for non-English locales

### ISSUE THREAD

**Issue by LaurentTreguier** [microsoft/testfx#4006]
## Describe the bug

Using `MSTest.Adapter` and `MSTest.TestFramework` at version 3.6.2

## Steps To Reproduce

1. Use a non-English locale (for example, French)
2. Create a new WinUI 3 project in Visual Studio
3. Add a test project to the solution
4. Update the test project's dependencies to the latest versions
5. Try to build and run the tests

## Expected behavior

The project should build and execute the example test cases.

## Actual behavior

The build fails with `APPX1101`; multiple DLLs are duplicated between `MSTest.Adapter` and `MSTest.TestFramework`.

## Additional context

The key to the problem seems to be the system locale. All of the duplicated DLL files during my testing were under `fr` subdirectories, found inside for example the `mstest.testadapter\3.6.2\build\_localization` and `mstest.testframework\3.6.2\lib\net8.0` directories. Those do not contain anything for English locales, hence why the issue doesn't seem to arise on a system with an English locale set.

**Comment by nohwnd** [comment]
Thanks for reporting, this is most likely related to this change that fixed copying the resource files, they were not copied properly before. https://github.com/microsoft/testfx/pull/3949 

And caused by the filter in this change https://github.com/microsoft/testfx/pull/3874 not being strict enough. It should most likely not copy the Framework or ObjectModel dlls.

**Comment by nohwnd** [comment]
https://github.com/microsoft/testfx/pull/3874 is not on 3.6 at all, backporting and fixing.
