### ISSUE TITLE
TestContext (MSTEST0005) is enforced to be case-sensitive

### ISSUE THREAD

**Issue by stan-sz** [microsoft/testfx#4428]
## Describe the bug

With 3.7 release, the TestContext (MSTEST0005) is enforced to be case-sensitive. According to the docs, https://learn.microsoft.com/en-us/dotnet/core/testing/mstest-analyzers/mstest0005, it is meant to be case insensitive).

## Steps To Reproduce

Create a test class with

```csharp
public TestContext testContext { get; set; }
```

## Expected behavior

No MSTEST0005

## Actual behavior

MSTEST0005 is raised

**Comment by Youssef1313** [comment]
@stan-sz Thanks for reporting this.

Putting the analyzer behavior aside, is the `testContext` property actually set when it's named `testContext` and not `TestContext`?

I think the current analyzer behavior is correct and TestContext was probably never set when the name is `testContext`. But let me know if you see otherwise (preferably with a repro project).

**Comment by Evangelink** [comment]
Just did a quick test and looks like this is a doc issue. @Youssef1313 please try to confirm with 3.2 or 3.3.

**Comment by Youssef1313** [comment]
I opened a PR to increase our test coverage for this case, and opened a docs PR to fix the misleading information as well. Thanks again @stan-sz for bringing this to our attention.

**Comment by Youssef1313** [comment]
I'm closing as the docs PR is merged, as well as the test coverage PR. @stan-sz Feel free to re-open and let us know if there are more issues on this topic. Thanks again for bringing it to our attention!
