### ISSUE TITLE
TestDeploymentDir nuget vs docs?

### ISSUE THREAD

**Issue by CasperWSchmidt** [microsoft/testfx#517]
According to #455 TestDeploymentDir is not yet implemented (but part of #96), but looking at https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.testcontext.testresultsdirectory?view=mstest-net-1.3.2#Microsoft_VisualStudio_TestTools_UnitTesting_TestContext_TestResultsDirectory it looks like it should be there (in namespace Microsoft.VisualStudio.TestTools.UnitTesting)? I have checked that my version of MSTest v2 is 1.3.2 and I'm using that exact same namespace but the property is not there. Are the docs wrong or am I confused?

**Comment by karanjitsingh** [comment]
@CasperWSchmidt, are you trying this with netcore build or the desktop/net45x build?
It's only implemented for the desktop i.e. net45x build of mstest: https://github.com/Microsoft/testfx/search?q=TestResultsDirectory&unscoped_q=TestResultsDirectory

I guess since we haven't mentioned that specifically in the docs, they're misleading.
FYI: @PBoraMSFT

**Comment by PBoraMSFT** [comment]
@karanjitsingh @jayaranigarg - I believe Jaya was looking at a similar report from earlier and fixing the MSTest docs.
Once the docs are updated, please mark this issue as an enhancement to make available for netcore as well.

**Comment by CasperWSchmidt** [comment]
@karanjitsingh I'm targeting .net standard 2.0 at the moment :)

**Comment by jayaranigarg** [comment]
https://github.com/Microsoft/testfx-docs/blob/master/RFCs/009-DeploymentItem-Attribute.md
