### ISSUE TITLE
Assembly location of dependent assemblies appears to be inconsistent

### ISSUE THREAD

**Issue by nigelgbanks** [microsoft/testfx#553]
## Description

When a **Test Project** depends on **Library Project**, and the **Library Project** calls `System.Reflection.Assembly.GetExecutingAssembly().Location` to get the path of a itself while executing, the behavior across versions is inconsistent.

When using _version 1.2_ of the MSTest Adapter the call above yields the _"Test Out Path"_ of the running test which is expected.

When using _versions 1.3_ or greater, it gets the _"Build Output Path"_ folder where MSBuild placed the executable (i.e. bin/Debug), which is unexpected. 

Also if "DeploymentItem" annotation is **not** used, then version does not matter, the assembly location appears to be the _"Build Output Path"_.

## Steps to reproduce

I've attached a simple solution that show this. To quickly test between the versions. Open the Visual Studio "Developer Command Prompt" and run either "pass.bat" or "fail.bat" to see the different behavior. 

[bug.zip](https://github.com/Microsoft/testfx/files/2760889/bug.zip)

Alternatively you can choose the build configuration
 and version using "build.bat" like so:

```bash
build.bat Release 1.2.1
build.bat Debug 1.4.0
build.bat Release 1.3.2
```

This is .net 4.5 for desktop.

## Expected behavior

The location of loaded dependent assemblies should match that of the _"Test Out Path"_ as they get deployed to that location along with the test assembly.

## Actual behavior

The location of loaded dependent assemblies varies depending on the MSTest version, and if files have been deployed or not.

## Environment

Windows 10
Visual Studio 2017 - 15.5.9
vstest.console.exe - 15.9.0

**Comment by nigelgbanks** [comment]
I haven't found any other ticket associated with this but I've found the issue referenced in comments [here](https://github.com/Microsoft/testfx/issues/526#issuecomment-446131270)

**Comment by mayankbansal018** [comment]
@nigelgbanks We investigated this issue, & we agree that this behavior has changed. However, the reason we had to take this breaking change is because of other severe issues that would occur, when users were using multiple versions of MsTest Framework/Adapter in their Unit test projects.

Also as you have read from other comment, this behavior is caused due to multiple appdomains that get created, & resetting their appbase path, doesn't work as needed.

Going forward we recommend that you use `<DisableAppDomain>` configuration as true. The behavior with this flag is consistent across adapter versions.

Also for this specific case, since you are relying on GetCurrentAssembly location, we assume you would be using it further in your code, we suggest that you use TestContext propertie(s) for such requirements
