### ISSUE TITLE
ThrowsException overload related suggestions

### ISSUE THREAD

**Issue by ymh199478** [microsoft/testfx#612]
## Description

Is it possible to add an exception assertion like this in the future:

- src/TestFramework/MSTest.Core/Assertions/Assert.cs
```csharp
Exception ThrowsException(Type expected, Action action, string message, params object[] parameters);
```

This can be very useful when driving data.

At the same time, it is also very helpful to establish the extension method of `ThrowsException` on this basis.

**Comment by jayaranigarg** [comment]
@yb199478 : We do have an [ExpectedExceptionAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.expectedexceptionattribute?view=mstest-net-1.2.0) which you can use to provide what kind of exception you are expecting your test to throw.

Also, MSTest framework provides extensibility for writing your own custom assertions. [Here ](https://github.com/microsoft/testfx-docs/blob/master/RFCs/002-Framework-Extensibility-Custom-Assertions.md) is the RFC doc for same. For example, you can refer these files : https://github.com/microsoft/testfx/blob/master/test/E2ETests/TestAssets/FxExtensibilityTestProject/AssertExTest.cs and https://github.com/microsoft/testfx/blob/master/samples/FxExtensibility/AssertEx.cs

**Comment by yb199478** [comment]
I have learned about `ExpectedExceptionAttribute` and `ExpectedExceptionBaseAttribute`, but it may not be so friendly when data is driven.

Although it can solve this problem through [custom assertions(rfc002)](https://github.com/Microsoft/testfx-docs/blob/master/RFCs/002-Framework-Extensibility-Custom-Assertions.md), it doesn't feel so elegant. 

I think `Assert.ThrowsException` may be better with `Type` as the exception type, rather than just providing an assertion through the template method. This will be more conducive to expansion than the template method.

This is just some of my suggestions, thanks.

**Comment by jayaranigarg** [comment]
@yb199478 : Thank you for your suggestion. Getting in feature as first-class support in MsTest wil happen purely on the basis of no. of asks from community. We will surely prioritize this if we have enough votes.

**Comment by Evangelink** [comment]
It looks like this is a stale issue. MSTest now has `ThrowsException` overloads with `Action` or `Func` (see https://learn.microsoft.com/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert.throwsexception).
