### ISSUE TITLE
Assembly search paths seems to be wrong when using DeploymentDirectory

### ISSUE THREAD

**Issue by Daniel-Svensson** [microsoft/testfx#653]
This is from one part of https://github.com/microsoft/testfx/issues/552 which was closed.

_Originally posted by @Daniel-Svensson in https://github.com/microsoft/testfx/issues/552#issuecomment-504991415_

@ShreyasRmsft 

There is now a repro in https://github.com/Daniel-Svensson/MsTestRepro for my "other" bug which currently prevents me from producing a repro of my original issue.
I will try to extract this to a separate issue.

Open the sln file in VS2017 (15.9) build and run all tests from within test explorer.

Actual behaviour:
* The tests fails
* if you only run the test without [DeploymentItem] it will succeed

Expected behaviour
* The tests should pass

Observations:
* The assembly load seems to be loading assemblies from the wrong assembly path (from bin directory instead of the TestResult/Out directory, so I suspect it is related to the testadapter code)
* This seems to be working if you use VS 2019 (and probably also for VS 2015) (I haven't tried the actual repro project in either of them but the original code seems to work)
* It should work with mstestv1
* Running tests from azure pipelines also triggers the issue so it is not VS specific

**Comment by ShreyasRmsft** [comment]
@singhsarab @jayaranigarg I think this issue also can be solved by using appdomain.load with the path.

The symptoms are similar. The appdomain base is set to bin where the adapter is present. But the tests are running from the "out" folder because of deployment Items.

@Daniel-Svensson we have a fix in mind that we'll try out in the next few days. If that works your issue should also get resolved along with a few other related ones.

**Comment by seekingtheoptimal** [comment]
I can confirm we had the same issue with simple assembly references:
We had the Microsoft DacFx as common, and 3 different test assemblies. DacFx scans its directory for any other dlls containing code analysis rules.
On VS2019 worked fine, but on Azure Devops and in VS2017 only the test assembly that was run first succeeded, all the other failed because they didn't contain any rules scanned and imported by DacFx.
The cause is the same as in this issue and as in the related closed one: the common assembly was loaded once, and then always used from the same place, regardless of the location of the independent test assemblies.

**Comment by Daniel-Svensson** [comment]
@seekingtheoptimal you might be interested in #57 that would solve many similar issues (but not exactly this issue where wrong location is used)

**Comment by Evangelink** [comment]
@Daniel-Svensson Sorry for the huge delay in handling this issue. I just cloned your repository and tried to run from VS2022 and the 2 tests are green:
<img width="952" alt="screenshot-VS2022-mstest1" src="https://user-images.githubusercontent.com/11340282/204525577-7a6480c3-c048-4042-ba88-e5b0e4dd8ce0.png">


I have also tried using latest MSTest (2.2.10) and latest test SDK (17.4.0):
<img width="959" alt="screenshot-VS2022-mstest2" src="https://user-images.githubusercontent.com/11340282/204525458-05ef9984-10dd-45b7-ab03-eeac364eb464.png">
