### ISSUE TITLE
Test discovery slow on large projects

### ISSUE THREAD

**Issue by captainjono** [microsoft/testfx#700]
I am working with a legacy VS solution with ~150projects / ~10k+ files. Its not ideal, but its what I have to work with. Test discovery can take between 40-120secs after every compile, and its even worse when JustMock is enabled....

Ive done some experiments and found if i patch the test discoverer to only iterate assembles with "*.tests.dll" in their filename, discovery time drops to ~4sec on the same 150 project solution.

This is a similar spot where i have applied the patch in other adapters.
https://github.com/microsoft/testfx/blob/efa1a6d93497719b51ada27787d7f6fcfdd24afe/src/Adapter/MSTest.CoreAdapter/MSTestDiscoverer.cs#L44

I wanted to understand, Is running a patched adapter my only chance at salvation? Or are there any public APIs i can use to achieve the same thing? Us large project folks dont get any love from the VS team, their advice is always to reduce the size. Which i cant.

**Comment by nohwnd** [comment]
Hello, thanks for reporting, this is a pain point that is easy enough to solve on command line by providing a filter, but not easy to overcome in VS because there is no place to specify that filter. The sources (dlls) that should be inspected are provided by the test platform, so that is where we need to do the filtering, to reduce the amount of them.

It would help if you filed a feedback ticket, I don't see one that would be exactly like yours and was not closed: 

https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=test+discovery+slow

**Comment by captainjono** [comment]
Done
