### ISSUE TITLE
NUnit tests not discovered in VS2019.5

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#701]
Update to VS2019.5 and my NUnit tests are gone. Since I was using ReSharper to run I tried running with the NUnit plugin and it couldn't run the unit tests either. Rider cannot discover the tests either.

Error message 'vs-test case is missing' may display.

Was there a path change with the latest update or maybe a change to .net core 2.1 causing the environment to not be able to discover the tests?

_Originally posted by @ekennedy6334 in https://github.com/microsoft/testfx/issues/668#issuecomment-600778508_

**Comment by nohwnd** [comment]
@ekennedy6334  moved your issue here so we don't revive the closed issue. 

Would you have a simple repro that I can try to see if I have the same behavior? Please list the versions of dotnet that you use (`dotnet --version` run this in the project folder), the target framework (such as netcoreapp3.1 in your csproj), and the versions of nunit (also in your csproj).

**Comment by ekennedy6334** [comment]
dotnet -- version returns 3.1.200

The project is - netcoreapp2.1
nunit - version:3.12.0
NUnit3TestAdapter - version:3.15.1
Microsoft.NET.Test.Sdk - version:16.4.0

By changing to  netcoreapp3.1 the unit tests are discovered. So the issue seems to be something changed in the latest update to 2.1.? that's breaking discovery.
