### ISSUE TITLE
Is there an approved/recommended way to run MSTests progammatically?

### ISSUE THREAD

**Issue by jameswiseman76** [microsoft/testfx#733]
Hi, I'm trying to run MSTest programmatically, and am feeling like I'm going down a rabbit warren somewhat.

I've have a reference github repo https://github.com/jameswiseman76/UnitTestRunnerApiAdaptor, where I am trying to this. I found an article (https://social.msdn.microsoft.com/Forums/en-US/ccd08ce1-a86b-4965-af68-1db8cd7d6715/how-to-execute-test-methods-programmatically-using-c-may-be-using-reflection) that seemed to suggest I should pull in a couple of dependency dlls under the Visual Studio installation, and gave some sample source code to integrate:

In following these instructions, it seems to want me to pull in all of the following (2 more that the article above suggests)
- C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
- C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.dll
- C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll
- C:\Program Files (x86)\Microsoft Visual Studio\Shared\Packages\MSTest.TestFramework.1.2.0\lib\net45\Microsoft.VisualStudio.TestPlatform.TestFramework.dll

I can **RunSingleTest** just fine, but **RunDataDrivenTest** throws the following exception:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration
  StackTrace:
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.UnitTestRunner.GetConnectionProperties(DataSourceAttribute dataSourceAttribute, String& providerNameInvariant, String& connectionString, String& tableName, DataAccessMethod& dataAccessMethod)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.UnitTestRunner.RunDataDrivenTestInternal(TestContextImplementation testContext, TestMethodInfo testMethodInfo, TestMethod testMethod)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.UnitTestRunner.RunInternal(TestMethod testMethod, Boolean isDataDriven, Dictionary`2 runParameters)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.UnitTestRunner.RunDataDrivenTest(String name, String fullClassName, Boolean isAsync, Dictionary`2 runParameters)
   at UnitTestRunnerApiAdaptor.MSTest.MSTestRunner.Run() in C:\Users\james\source\repos\jameswiseman76\UnitTestRunnerApiAdaptor\UnitTestRunnerApiAdaptor\MSTest\MSTestRunner.cs:line 41

```

After waoring with XUnit and NUnit, which have defined ways of doing this, is there something more formal for MSTest that I can use?

**Comment by nohwnd** [comment]
I am not sure on which level you are trying to implements this. There is VSTestConsoleWrapper that is used by tools (such as Stryker) to automate vstest.console. Vstest.console then invokes appropiate test host and runs tests via adapter in the given test framework, such as MSTest, xUnit or NUnit. With the wrapper you can run tests as  you would via VS, because the mechanisms are the same. 

Here is an example of using the wrapper: 

https://github.com/microsoft/vstest/blob/master/samples/Microsoft.TestPlatform.TranslationLayer.E2ETest/Program.cs

The example project references other projects in our solution, but you need the translation layer and vstest.console executable: 

You can grab the layer here: https://www.nuget.org/packages/Microsoft.TestPlatform.TranslationLayer/ And vstest.console executable from here: https://www.nuget.org/packages/Microsoft.TestPlatform This package is a good source for that, it is what vstest task uses on AzDO.

**Comment by nohwnd** [comment]
One caveat there to be aware of as well, if you don't provide any runsettings and just use empty string, it won't complain, but for some reason it won't run your callbacks. I wasted a whole afternoon on that once, and did not get any time to fix it yet.

**Comment by jameswiseman76** [comment]
Thanks, that's a great answer. I'll take a look into it.
