### ISSUE TITLE
2.2.5 regregssion: DynamicData method is called once, output is persisted between runs

### ISSUE THREAD

**Issue by abatishchev** [microsoft/testfx#902]
## Description

Having a data test method:

```c#
protected static readonly Guid _subscriptionId = Guid.NewGuid();

[DynamicData(nameof(GetData), DynamicDataSourceType.Method)]
[DataTestMethod]
public void MyTest1(Guid subscriptionId)
{
    // breakpoint A
}

private static IEnumerable<object[]> GetData()
{
    // breakpoint B
    yield return new object[]
    {
        _subscriptionId
    };
}
```

## Steps to reproduce

1. Run the test from Test Explorer -> Debug (Cltr+R, Ctrl+T)
2. Write down the values of `_subscription` and `subscription`
3. Run the test again
4. Write down the values of `_subscription` and `subscription` again

## Expected behavior

1. The values from run 1 are same
2. The values from run 2 are same
3. The values between runs are different

## Actual behavior

1. The values from run 1 are same
2. The values from run 2 are different!
3. `subscripotion` witch is a parameter coming from `GetData` is same across the runs
4. Breakpoint **B** is never hit!

## Environment

Windows 10 0.0.19043 Build 19043
Version 16.10.3, VisualStudio.16.Release/16.10.3+31424.327

```
vstest.console.exe /help
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.
```

```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
<PackageReference Include="MSTest.TestAdapter" Version="2.2.5" />
<PackageReference Include="MSTest.TestFramework" Version="2.2.5" />
```

Rolling back to the last known good version resolves the issue:

```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
<PackageReference Include="MSTest.TestAdapter" Version="2.2.3" />
<PackageReference Include="MSTest.TestFramework" Version="2.2.3" /
```
And don't forget to delete both `.vs` and `.obj` folders.

**Comment by Haplois** [comment]
Hi @abatishchev, 

We started to discover `DynamicData` tests on discovery step. That step run on a different context to actual test execution. (It can also be fetched from cache.) In your case, `static readonly` `_subscriptionId` initialized during discovery, and tests discovered with their parameters. During test execution, previously discovered parameters are used.

Can you describe how this affects your workflow?

**Comment by abatishchev** [comment]
Here's the major issue in facing:

1. Unable to debug the dynamic data source method. Regardless of other issue, this one is huge and must be fixed. It's not an `enhancement` per the tag the issue is marked with but a `bug`. Please take this seriously.
2. The dynamic data is apparently getting cached and it's unclear how to clear the cache. Is it documented? Why this is happening in the first place?
3. The fields initialization semantics has changed, from the default .NET behavior to something custom and specific to MSTest. Before a field was a field, it could be access in an arbitrary manner, whether it's a regular or dynamic data source method. Not anymore. Why?

@pavelhorak why any of the changes were made in a `patch` segment of the version? Aren't you following the SemVer rules in this project? MSTest is the default testing framework in .NET, including at Microsoft internally as well, and by updating to `x.y.5` people may and will have certain expectations. Which do not include major and/or breaking changes.
I apologize if I sound frustrated but I am. Past 2 updates were haunted with serious issues. I'd like to establish a healthy, working dialog with the team. So again, please take this issue seriously.

**Comment by Haplois** [comment]
@abatishchev, I am sorry for the issues you're having with this change. Introducing this change on a `patch` was our mistake. We'll be careful not to release breaking changes in `patch` updates and respect the SemVer contract.


> 1. Unable to debug the dynamic data source method. Regardless of other issue, this one is huge and must be fixed. It's not an enhancement per the tag the issue is marked with but a bug. Please take this seriously.

This is by-design, Visual Studio discovers and caches tests once and all the subsequent test runs (assuming no code change) will run the tests from cache. Currently if you need to debug discover phase, you can use the following code snippet:

```csharp
using System.Diagnostics;

private static IEnumerable<object[]> GetData()
{
    if (Debugger.IsAttached)
    {
        Debugger.Break();
    }
    else
    {
        Debugger.Launch();
    }

    yield return new object[] { _subscriptionId };
}
```

> 2. The dynamic data is apparently getting cached and it's unclear how to clear the cache. Is it documented? Why this is happening in the first place?

We'll be updating our documentation about these soon, currently no documentation exists. Cleaning or rebuilding the project/solution will clean the cache. We also have long term plans to add  "Clean Test Cache" and "Clean Test Results" functionality to Test Window.  We're working on improving the test run performance by eliminating test discovery, this is part of that work.

> 3. The fields initialization semantics has changed, from the default .NET behavior to something custom and specific to MSTest. Before a field was a field, it could be access in an arbitrary manner, whether it's a regular or dynamic data source method. Not anymore. Why?

Discovery and Execution are separate processes. In your example, discovery only happens once and field values are cached. Because of this you're seeing discrepancies between  `this._subscriptionId` and `subscriptionId` inside the test.

We'll be providing a way to opt-out from this discovery behavior while we're working on that you can continue using version 2.2.3. Opt-out functionality is tracked by #905.

I am closing this issue, please let us know if you have any other questions.
