### ISSUE TITLE
DataRow test throws excption

### ISSUE THREAD

**Issue by debabbe** [microsoft/testfx#915]
## Description
Unit tests are not working with DataRows and MSTests 2.2.5 in Visual Studio 2017
## Steps to reproduce

```csharp
[DataRow(true)]
[DataRow(false)]
[DataTestMethod]
public void Test(bool boolean)
{
    Assert.AreEqual(boolean, boolean);
}
```

See [https://github.com/debabbe/DateRowError](https://github.com/debabbe/DateRowError)

This simple test is not working. Unit test fails with the error: 
Message: Fehler beim Deserialisieren des Objekts "vom Typ System.Object". Unerwartetes Zeichen 'S'.
## Expected behavior
Tests have to work.

## Environment
Window 10
MSTest 2.2.5
Visual Studio 2017

**Comment by jr01** [comment]
This issue should be fixed by https://github.com/microsoft/testfx/pull/998 .  It got merged after 2.2.7 was released ...

**Comment by Haplois** [comment]
This issue is fixed, if you're still having it could you please share a sample repro @krilbe? Also as @jr01 mentioned there were more fixes released with 2.2.8, it might help with your issue to update.

If the issue is generally about how we process DataRow tests, you can opt-out of the behavior by adding this assembly level attribute anywhere on your test project:

```csharp
[assembly: TestDataSourceDiscovery(TestDataSourceDiscoveryOption.DuringExecution)]
```

**Comment by debabbe** [comment]
It's working now. Thanks all

**Comment by debabbe** [comment]
It's working now. Thanks all
