### ISSUE TITLE
Enable discovery of internal test classes

### ISSUE THREAD

**Issue by cimryan** [microsoft/testfx#934]
My team finds it convenient to extract tests for common attributes into reusable, abstract, generic classes and inherit from these classes in the type-specific tests. This approach doesn’t work for internal types, however, because the test class must be public in order for MSTest to discover it.

In the below example, FancyString is not intended to be a public type of the assembly. (It’s marked internal just so that it can be tested.) Because FancyString is marked internal, it’s a compile-time error to mark the class FancyStringsAreCaseInsensitive as public. But since FancyStringsAreCaseInsensitive is marked internal it’s not discovered.

FancyStringTests.cs:
```C#
using System;
using DevProject1;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject1
{
    [TestClass]
    public class FancyStringTests
    { 
        [TestClass]
        // This class will not be discovered by MSTest because it is internal rather than public.
        // But, since FancyString is internal, marking the test class public will produce a compilation error.
        // This forces us to either make FancyString public or abandon this technique for reusing test classes.
        internal class FancyStringsAreCaseInsensitive : CaseInsensitivityTests<FancyString>
        {
            protected override Tuple<FancyString, FancyString> EquivalentInstancesWithDistinctCasing { get; }
        }
    }
}
```

FancyString.cs:
```C#
using System;

namespace DevProject1
{
    internal class FancyString
    {
        // TODO
    }
}
```

CaseInsensitivityTests.cs:
```C#
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject1
{
    internal abstract class CaseInsensitivityTests<T>
    {
        protected abstract Tuple<T, T> EquivalentInstancesWithDistinctCasing { get; }

        [TestMethod]
        public void EqualityIsCaseInsensitive()
        {
            var (left, right) = EquivalentInstancesWithDistinctCasing;
            Assert.AreEqual(left, right);
        }

        [TestMethod]
        public void HashCodeIsCaseInsensitive()
        {
            // TODO
        }
    }
}
```

**Comment by Kalonjelen** [comment]
I'd recommend having it as an attribute like other Test type attributes that you can decorate at the class or the method level, like TestCategory. Then you can have similar logic to how [Ignore] works:
var typeIgnored = ReflectHelper.IsAttributeDefined(type, typeof(UTF.IgnoreAttribute), false);

My personal team would like some things to be tested with internals, and some things to not be, and these things do sometimes intermingle. Having it be an attribute on the class makes it a bit more intentional, IMO.

**Comment by cimryan** [comment]
I'm not sure we're discussing the same scenarios. Can you clarify what you mean by "things to be tested with internals"?

The capability that I want is for MSTest to discover the test methods in an internal class (which has been decorated with [TestClass]).

If there were no internal classes in the universe which were decorated with [TestClass] then the behavior of MSTest could just be changed for all cases, no setting necessary. But... https://xkcd.com/1172/

So the change in behavior has to be opt-in. But if you're opting in, you're making changes. And if you're making changes, why not just remove the [TestClass] attribute from the classes that you don't want to be treated as test classes? (Or use [Ignore] or private, as appropriate.) Having a class decorated with [TestClass] that you want to _not_ run seems like the opposite of intentionality, doesn't it?

Importantly, it's not necessary to have internal [TestClass] classes, today: Their tests can't run. So cleaning them up should be unambiguous. And, again, you only have to clean them up if you want different behavior for other tests in the project.

On the other hand, there's value in making this a project-level property: I want this behavior for all my tests without having to attach another attribute to each class.

**Comment by Kalonjelen** [comment]
Sorry, I will try and be more clear.

We have test projects which have some public classes that we'd like to test the regular way, AND we have some internal classes that we'd also like to test - and some other internal classes that we would emphatically not like to test or give access to. Currently we do wrappers around them as public classes for the ones we test, but it'd be nicer to not have to do that sort of wrangling. Now, we can simply remove the [TestClass] attribute from the internal classes that we don't want tested, and that's a reasonable suggestion - but if someone else decides to put in a [TestClass] attribute and we don't catch it in PR, it'll do the wrong thing if it's set at the project level. And that sort of thing is in my experience really easy to miss, especially if you're not aware of the project-level setting. 

Because right now, the [TestClass] decoration on an internal class _does nothing at all_. 

Whereas if you had something like [TestClassInternal] you could decorate the test classes that you wanted, have something that is self-documenting and intentional, and is at the actual level of the tests themselves. It would change zero behavior out there without explicitly opting in to those files. I think that gives more flexibility to the users of it.

**Comment by cimryan** [comment]
Thanks, I'm still trying to understand. You have classes in your project like this?

```C#
namespace Our.System.UnitTests
{
    [TestClass]
    internal class ABunchOfTests
    {
        [TestMethod]
        public void WhenTheMoonIsFull_TheDogHowls()
        {
            // TODO
        }
        [TestMethod]
        public void WhenTheMoonIsNew_TheDogSleeps()
        {
            // TODO
        }
    }
}
```

And you want neither ```WhenTheMoonIsFull_TheDogHowls``` nor ```WhenTheMoonIsNew_TheDogSleeps``` to be executed? Why not just delete the whole class?
